# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
  clean: true
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      git config --global user.email $EMAIL
      git config --global user.name $NAME
    noProfile: false
    noRc: false

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      npm run deploy
    noProfile: false
    noRc: false